### ISSUE TITLE
Cache cleanup strategy broken

### ISSUE THREAD

**Issue by burgerdev** [ilastik/lazyflow#185]
The current strategy for cache cleanup 

  1. Check current process memory usage `m`
  2. If `m` > `0.85*LAZYFLOW_TOTAL_RAM` throw out a cache
  3. repeat

does not work well when batch processing or exporting. When these operations occupy large areas of available memory themselves, all caches are thrown out and - worst case - there is an infinite request-throwout-request_again loop. I think that the memory consumption computation by `meta.ram_usage_per_requested_pixel` has its part in this[1], too, but we probably can't rely on that to work perfectly. 

Suggested fix: Target a **percentage of available memory for caches**. E.g.:

  1. Fix max memory `M` for caches (`.5*LAZYFLOW_TOTAL_RAM` ?)
  2. Check current cache memory usage `m`
  3. If `m>M` throw out a cache
  4. repeat from 2

[1]: I am using Pixel Classification + Object Prediction "from scratch". When exporting via the export applet, RAM used by ilastik goes up to 3 times more than allowed by `LAZYFLOW_TOTAL_RAM_MB`

**Comment by burgerdev** [comment]
There's an example implementation in the commit above, which enables me to run PC+OC with the drosophila3d+t dataset on my 8GB machine at home. Which I could not do before.

**Comment by stuarteberg** [comment]
>When these operations occupy large areas of available memory themselves, all caches are thrown out and - worst case - there is an infinite request-throwout-request_again loop.

I'm sorry, I think I'm missing something here.  How do we end up with an infinite loop?

>Suggested fix: Target a percentage of available memory for caches. E.g.:

Again, I'm confused.  How does specifying separate values for the cache RAM vs total RAM fix the problem?  I don't understand.

**Comment by burgerdev** [comment]
Infinite might be too much, "many iterations of filling and emptying" is more to the point.

Lets assume we have 1GB of memory for lazyflow and 4GB physically available. The `bigRequestStreamer´ calculates some block size which will fill the 1GB with computations. This triggers the `CacheMemoryManager`, which throws out caches until less than 1GB is used. Since 1GB is used for computations at the moment, there is no memory for caches, so all caches get thrown out. It is much likely that some cache *will* be needed again, and it has to be recomputed. Because upstream caches are also missing, many computation steps will be performed multiple times, effectively negating the whole purpose of the caches.

This can be prevented by having a dedicated amount of memory for caches. Did this clear things up?

**Comment by stuarteberg** [comment]
>Did this clear things up?

Yes, thanks.

From above:

>I think that the memory consumption computation by `meta.ram_usage_per_requested_pixel` has its part in this, too, but we probably can't rely on that to work perfectly. 

I think I implemented this field inaccurately in the case of cache operators (that feature was originally implemented and tested with pixel classification export in mind, which uses no caches).  Your idea to distinguish between "cache memory" and "computation memory" makes sense.  Should we split `ram_usage_per_requested_pixel` into two different fields?  Just brainstorming here...

**Comment by burgerdev** [comment]
That would make perfect sense. However, determining `ram_usage_per_requested_pixel` will still be hard, if not impossible, in object classification because of the non-lazy operators and the unpredictability of the lazy ones.

**Comment by stuarteberg** [comment]
>determining ram_usage_per_requested_pixel will still be hard, if not impossible

Agreed.  Do you have any ideas for solving this problem?  If I understand correctly, the current proposal is to just give the user more control over how much RAM to allocate to the caches, which implicitly limits the "computation memory" limit, which, in turn, will indirectly result in smaller computation block sizes during export.  (Is that right?)

Is there any way to save the user from this mess?  In the past, we've shied away from attempting to do "live sampling" of the RAM load during computation, because we assume it will be very difficult to get right.  Any alternative ideas here are welcome...

**Comment by burgerdev** [comment]
> [...] will indirectly result in smaller computation block sizes during export.  (Is that right?)

Yes, but I would consider this a beneficial side effect. My main goal in PR #186 is to ensure that important things can stay in memory *even when* RAM usage estimation goes wrong or photoshop is running in the background. Using @christophdecker's data, I was able to speed up the whole workflow significantly while keeping cache memory in control, effectively solving ilastik/ilastik#1075 and ilastik/ilastik#940 simultaneously.


> Is there any way to save the user from this mess?

I hope so. With a bit of experimentation I imagine we should be able to arrive at a fraction of RAM that is best reserved for caches and can be used as a default without user interaction. My observation so far was that, in PC+OC, caches contribute about 1/4 to total memory usage (don't ask me where the rest comes from...). If we decide to go for usability rather than performance, a variety of settings might work just fine. In case of performance-critical batch workflows on clusters we will have to fine-tune the trade-off between memory and processing time, but we have to do that anyway, right?

> In the past, we've shied away from attempting to do "live sampling" of the RAM load during computation, because we assume it will be very difficult to get right.

I agree with that. Out of my limited perspective I could think of switching from `ram_usage_per_requested_pixel` to `ram_usage_per_requested_block`, which simplifies predicting RAM usage for blocked operators like `OpLazyConnectedComponents`.
