### ISSUE TITLE
CircleCI pull request check not working

### ISSUE THREAD

**Issue by burgerdev** [ilastik/lazyflow#190]
In [this build](https://circleci.com/gh/ilastik/lazyflow/11), CircleCI should have tested the branch burgerdev:fix-tifffile-import. Instead, it tested lazyflow:master because of [this line](https://github.com/ilastik/lazyflow/blob/master/circle.yml#L26). It would be nice if we could make the `circle.yml` simpler and fully benefit from the GitHub integration.

**Comment by stuarteberg** [comment]
Should be fixed via 9829c8b66a5fc19a02d9ee15a05b573baacc95f5 and  ad2144568e4d9ab7b065b888129839f402c70ac1
