### ISSUE TITLE
numpy version check 

### ISSUE THREAD

**Issue by akreshuk** [ilastik/lazyflow#218]
in hessian_eigenvectors.py, the check is made like:
`assert numpy.__version__ >= '1.8.0'`
Obviously, it would fail now that we have 1.11.1. This issue is trivial to fix, but we should check for such asserts all over.

**Comment by stuarteberg** [comment]
Ah, good point.  BTW: I don't think we're actually using `hessian_eigenvectors()` anywhere. (I thought I would use it in the IIBoost workflow, but I didn't need it in the end.)

Are you using that function?  If so, we should consider creating an ND python API for  `vigra::linalg::symmetricEigensystem()`, which might be faster.  In the mean time, you can try `iiboost.computeEigenVectorsOfHessianImage()`, which is already exposed to Python (see `opIIBoostFeatureSelection.py` for example usage.)
