### ISSUE TITLE
Deadlocks in ArrayCache memory management code

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/lazyflow#79]
The ArrayCacheMemoryMgr class and OpArrayCache work cooperatively to implement an LRU cache replacement strategy.  This code needs review and thorough testing.  Deadlocks inevitably occur during long memory-intensive batch jobs.  An inspection of the code reveals multiple opportunities for lock order inversion to occur, involving ArrayCacheMemoryMgr._lock, OpArrayCache._lock, and OpArrayCache._cacheLock, which are presumably the source of the deadlocks.

**Comment by burgerdev** [comment]
I think the deadlock is caused by

```python
class OpArrayCache:
    def _freeMemory(self):
        with self._cacheLock:
            # ...
            with self._lock:
                # ...

    def setupOutputs(self):
        with self._lock:
            # call _allocateCache()

    def setinSlot(self):
        with self._lock:
            # call _allocateCache()

    def _allocateCache(self):
        with self._cacheLock:
            # ....
```

**Comment by burgerdev** [comment]
The `_cacheLock` seems to be used exclusively when `_lock` is acquired, I guess it is not needed.
